/* ADIP Tools v6.1.0 — manifest metadata (GENERATED, jangan edit manual).
   Dibangkitkan oleh scripts/sync-manifest.js dari meta tiap file tool.
   Berisi metadata ringan untuk home/search/palette; kode tool di-load on-demand.
*/
export const VERSION = '6.1.0';
export const manifest = [
  {"id":"banding-harga","name":"Perbandingan Harga","cat":"bisnis","icon":"⚖️","desc":"Mana lebih hemat per unit?","keywords":"banding,harga,murah,hemat,unit,belanja","file":"tools/bisnis/banding-harga.js"},
  {"id":"cat-tembok","name":"Kalkulator Cat","cat":"bisnis","icon":"🪣","desc":"Kebutuhan cat dari luas ruangan.","keywords":"cat,tembok,dinding,ruangan,renovasi","file":"tools/bisnis/cat-tembok.js"},
  {"id":"harga-jual","name":"Kalkulator Harga Jual","cat":"bisnis","icon":"💰","desc":"Modal + margin jadi harga jual.","keywords":"harga,jual,modal,margin,untung,jualan","file":"tools/bisnis/harga-jual.js"},
  {"id":"invoice","name":"Invoice Generator","cat":"bisnis","icon":"📑","desc":"Bikin invoice rapi siap cetak.","keywords":"invoice,tagihan,nota,kwitansi,cetak","file":"tools/bisnis/invoice.js"},
  {"id":"kpr","name":"Simulasi KPR","cat":"bisnis","icon":"🏠","desc":"Simulasi cicilan KPR + tabel angsuran.","keywords":"kpr,rumah,cicilan,kredit,angsuran,bank","file":"tools/bisnis/kpr.js"},
  {"id":"base64","name":"Base64 Encode/Decode","cat":"converter","icon":"🔤","desc":"Encode & decode Base64, termasuk varian URL-safe.","keywords":"base64,encode,decode","file":"tools/converter/base64.js"},
  {"id":"case-converter","name":"Case Converter","cat":"converter","icon":"✏️","desc":"camelCase, snake_case, kebab-case, Title Case, dll.","keywords":"case,huruf,camel,snake,kebab,kapital","file":"tools/converter/case-converter.js"},
  {"id":"color-converter","name":"Konverter Warna","cat":"converter","icon":"🎨","desc":"Konversi HEX, RGB, HSL + preview.","keywords":"warna,color,hex,rgb,hsl","file":"tools/converter/color-converter.js"},
  {"id":"cooking-converter","name":"Takaran Masak","cat":"converter","icon":"🍳","desc":"Konversi sendok, cup, gram, ml.","keywords":"masak,takaran,sendok,cup,gram,resep,dapur","file":"tools/converter/cooking-converter.js"},
  {"id":"csv-json","name":"CSV ↔ JSON","cat":"converter","icon":"🔄","desc":"Konversi CSV ke JSON dan sebaliknya.","keywords":"csv,json,konversi,data,spreadsheet,excel","file":"tools/converter/csv-json.js"},
  {"id":"image-base64","name":"Gambar ke Base64","cat":"converter","icon":"🖼️","desc":"Gambar jadi string Base64 siap embed.","keywords":"gambar,base64,foto,embed","file":"tools/converter/image-base64.js"},
  {"id":"json-yaml","name":"JSON ↔ YAML","cat":"converter","icon":"⇄","desc":"Konversi JSON ke YAML dan sebaliknya.","keywords":"json,yaml","file":"tools/converter/json-yaml.js"},
  {"id":"morse","name":"Sandi Morse","cat":"converter","icon":"📻","desc":"Teks ↔ sandi Morse + bunyi.","keywords":"morse,sandi,kode","file":"tools/converter/morse.js"},
  {"id":"number-converter","name":"Konverter Angka","cat":"converter","icon":"🔢","desc":"Biner, oktal, desimal, hex, dan romawi.","keywords":"angka,biner,hex,romawi,desimal,oktal","file":"tools/converter/number-converter.js"},
  {"id":"slug-generator","name":"Slug Generator","cat":"converter","icon":"🏷️","desc":"Judul jadi slug URL yang rapi.","keywords":"slug,url,judul,link","file":"tools/converter/slug-generator.js"},
  {"id":"terbilang","name":"Terbilang Indonesia","cat":"converter","icon":"💬","desc":"Angka jadi kata bahasa Indonesia.","keywords":"terbilang,angka,kata,rupiah","file":"tools/converter/terbilang.js"},
  {"id":"unit-converter","name":"Konverter Satuan","cat":"converter","icon":"📏","desc":"Panjang, berat, suhu, volume, kecepatan.","keywords":"satuan,konversi,panjang,berat,suhu,km,mile","file":"tools/converter/unit-converter.js"},
  {"id":"unix-timestamp","name":"Unix Timestamp","cat":"converter","icon":"🕰️","desc":"Unix timestamp ↔ tanggal (WIB).","keywords":"unix,timestamp,waktu,epoch","file":"tools/converter/unix-timestamp.js"},
  {"id":"url-encoder","name":"URL Encoder/Decoder","cat":"converter","icon":"🔗","desc":"Encode/decode URL & komponennya.","keywords":"url,encode,decode,link","file":"tools/converter/url-encoder.js"},
  {"id":"barcode","name":"vCard QR & Barcode","cat":"desain","icon":"🧾","desc":"QR kontak vCard & barcode produk.","keywords":"barcode,vcard,qr,kontak","file":"tools/desain/barcode.js"},
  {"id":"boxshadow","name":"Box-Shadow Generator","cat":"desain","icon":"🌓","desc":"Atur bayangan visual + copy CSS.","keywords":"box,shadow,bayangan,css","file":"tools/desain/boxshadow.js"},
  {"id":"clamp","name":"CSS Clamp Generator","cat":"desain","icon":"📏","desc":"Font responsif fluid dengan clamp().","keywords":"clamp,css,font,responsif","file":"tools/desain/clamp.js"},
  {"id":"favicon","name":"Favicon Generator","cat":"desain","icon":"⭐","desc":"Bikin favicon dari emoji/teks.","keywords":"favicon,icon,emoji,website","file":"tools/desain/favicon.js"},
  {"id":"gradient","name":"Gradient Generator","cat":"desain","icon":"🌈","desc":"Bikin gradient CSS + preview.","keywords":"gradient,gradasi,css,warna","file":"tools/desain/gradient.js"},
  {"id":"kontras","name":"Cek Kontras Warna","cat":"desain","icon":"◐","desc":"Rasio kontras WCAG AA/AAA.","keywords":"kontras,wcag,warna,aksesibilitas","file":"tools/desain/kontras.js"},
  {"id":"palette","name":"Color Palette Generator","cat":"desain","icon":"🎨","desc":"Palet warna harmonis sekali klik.","keywords":"palette,palet,warna,harmonis","file":"tools/desain/palette.js"},
  {"id":"qr-generator","name":"QR Code Generator","cat":"desain","icon":"🔲","desc":"QR Code teks, URL, & WiFi.","keywords":"qr,barcode,scan,link,wifi","file":"tools/desain/qr-generator.js"},
  {"id":"chmod","name":"Kalkulator Chmod","cat":"developer","icon":"🔒","desc":"Permission oktal ↔ simbolik.","keywords":"chmod,permission,linux,server","file":"tools/developer/chmod.js"},
  {"id":"cron","name":"Cron Parser & Builder","cat":"developer","icon":"⏰","desc":"Terjemahkan & susun cron expression.","keywords":"cron,jadwal,server","file":"tools/developer/cron.js"},
  {"id":"dns-lookup","name":"DNS Lookup","cat":"developer","icon":"📡","desc":"Lookup DNS via Google DNS-over-HTTPS.","keywords":"dns,domain,lookup,website","file":"tools/developer/dns-lookup.js"},
  {"id":"html-table","name":"Generator Tabel HTML","cat":"developer","icon":"📋","desc":"Bikin tabel HTML dari data baris.","keywords":"html,tabel","file":"tools/developer/html-table.js"},
  {"id":"json-formatter","name":"JSON Formatter","cat":"developer","icon":"🧩","desc":"Rapikan, minify, & validasi JSON.","keywords":"json,format,rapi,validasi","file":"tools/developer/json-formatter.js"},
  {"id":"json-table","name":"JSON ke Tabel","cat":"developer","icon":"📊","desc":"Paste JSON jadi tabel yang enak dibaca.","keywords":"json,tabel","file":"tools/developer/json-table.js"},
  {"id":"jwt-parser","name":"JWT Parser","cat":"developer","icon":"🎫","desc":"Baca isi header & payload JWT.","keywords":"jwt,token,auth","file":"tools/developer/jwt-parser.js"},
  {"id":"markdown-preview","name":"Markdown Preview","cat":"developer","icon":"📝","desc":"Preview Markdown jadi HTML.","keywords":"markdown,preview","file":"tools/developer/markdown-preview.js"},
  {"id":"meta-generator","name":"Meta Tag Generator","cat":"developer","icon":"🏷️","desc":"Generator meta tag SEO lengkap.","keywords":"meta,seo,tag,website","file":"tools/developer/meta-generator.js"},
  {"id":"og-preview","name":"Open Graph Preview","cat":"developer","icon":"👁️","desc":"Preview tampilan link di medsos.","keywords":"og,preview,link,sosmed,medsos","file":"tools/developer/og-preview.js"},
  {"id":"regex-tester","name":"Regex Tester","cat":"developer","icon":"🔍","desc":"Tes regex + highlight hasil.","keywords":"regex,tes,pola","file":"tools/developer/regex-tester.js"},
  {"id":"robots-generator","name":"Robots.txt Generator","cat":"developer","icon":"🤖","desc":"Susun file robots.txt.","keywords":"robots,seo,txt","file":"tools/developer/robots-generator.js"},
  {"id":"sql-formatter","name":"SQL Formatter","cat":"developer","icon":"🗄️","desc":"Rapikan query SQL.","keywords":"sql,query,database","file":"tools/developer/sql-formatter.js"},
  {"id":"subnet","name":"Kalkulator Subnet IPv4","cat":"developer","icon":"🌐","desc":"Network, broadcast, range host dari CIDR.","keywords":"subnet,ip,network,cidr","file":"tools/developer/subnet.js"},
  {"id":"xml-formatter","name":"XML Formatter","cat":"developer","icon":"📰","desc":"Rapikan & validasi XML.","keywords":"xml,format","file":"tools/developer/xml-formatter.js"},
  {"id":"zerowidth","name":"Detektor Karakter Tak Terlihat","cat":"developer","icon":"👻","desc":"Temukan zero-width & karakter aneh di teks.","keywords":"zerowidth,karakter,tersembunyi,invisible","file":"tools/developer/zerowidth.js"},
  {"id":"baby-name","name":"Nama Bayi","cat":"fun","icon":"👶","desc":"Nama bayi Indonesia + arti.","keywords":"bayi,nama,arti,anak","file":"tools/fun/baby-name.js"},
  {"id":"couple-days","name":"Hari Jadian","cat":"fun","icon":"💑","desc":"Sudah berapa hari bareng?","keywords":"jadian,pacar,pasangan,hari,anniversary","file":"tools/fun/couple-days.js"},
  {"id":"decision","name":"Pengacak Keputusan","cat":"fun","icon":"🔮","desc":"Bantu ambil keputusan.","keywords":"keputusan,acak,pilih,random","file":"tools/fun/decision.js"},
  {"id":"dice","name":"Dadu","cat":"fun","icon":"🎲","desc":"Lempar dadu + riwayat.","keywords":"dadu,acak,random","file":"tools/fun/dice.js"},
  {"id":"reaction","name":"Tes Refleks","cat":"fun","icon":"⚡","desc":"Ukur kecepatan refleks.","keywords":"refleks,reaksi,cepat,tes","file":"tools/fun/reaction.js"},
  {"id":"spinwheel","name":"Roda Putar","cat":"fun","icon":"🎡","desc":"Spin wheel visual.","keywords":"roda,putar,spin,acak,undian","file":"tools/fun/spinwheel.js"},
  {"id":"aspect-ratio","name":"Kalkulator Rasio","cat":"gambar","icon":"📐","desc":"Rasio aspek & resolusi.","keywords":"rasio,aspek,resolusi,ukuran","file":"tools/gambar/aspect-ratio.js"},
  {"id":"blur-foto","name":"Blur Foto (Sensor)","cat":"gambar","icon":"🫣","desc":"Sensor area foto dengan blur pixel.","keywords":"blur,sensor,foto,pixel,privasi","file":"tools/gambar/blur-foto.js"},
  {"id":"exif-clean","name":"Hapus EXIF","cat":"gambar","icon":"🧹","desc":"Bersihkan metadata sebelum dishare.","keywords":"exif,metadata,bersih,privasi","file":"tools/gambar/exif-clean.js"},
  {"id":"image-compress","name":"Kompres Gambar","cat":"gambar","icon":"🗜️","desc":"Kecilkan ukuran foto langsung di HP.","keywords":"kompres,gambar,foto,kecil,ukuran","file":"tools/gambar/image-compress.js"},
  {"id":"image-convert","name":"Convert Gambar","cat":"gambar","icon":"🔁","desc":"Convert WebP/JPG/PNG di browser.","keywords":"convert,gambar,webp,jpg,png,format","file":"tools/gambar/image-convert.js"},
  {"id":"meme","name":"Meme Generator","cat":"gambar","icon":"😂","desc":"Bikin meme teks atas-bawah + unduh PNG.","keywords":"meme,lucu,gambar,teks","file":"tools/gambar/meme.js"},
  {"id":"yt-thumbnail","name":"Thumbnail YouTube","cat":"gambar","icon":"📺","desc":"Download thumbnail YouTube dari URL.","keywords":"youtube,thumbnail,gambar,unduh","file":"tools/gambar/yt-thumbnail.js"},
  {"id":"arisan","name":"Arisan Picker","cat":"indonesia","icon":"🎰","desc":"Kocok nama anggota arisan.","keywords":"arisan,kocok,nama,acak","file":"tools/indonesia/arisan.js"},
  {"id":"bunga-majemuk","name":"Bunga Majemuk","cat":"indonesia","icon":"📈","desc":"Simulasi compound interest.","keywords":"bunga,majemuk,investasi,compound","file":"tools/indonesia/bunga-majemuk.js"},
  {"id":"cicilan","name":"Kalkulator Cicilan","cat":"indonesia","icon":"🏍️","desc":"Simulasi cicilan flat & anuitas.","keywords":"cicilan,kredit,motor,angsuran","file":"tools/indonesia/cicilan.js"},
  {"id":"countdown","name":"Countdown Acara","cat":"indonesia","icon":"🎉","desc":"Hitung mundur ke hari penting.","keywords":"countdown,hitung,mundur,acara","file":"tools/indonesia/countdown.js"},
  {"id":"diskon","name":"Diskon Bertingkat","cat":"indonesia","icon":"💸","desc":"Hitung diskon berlapis yang benar.","keywords":"diskon,promo,potongan,belanja","file":"tools/indonesia/diskon.js"},
  {"id":"format-hp","name":"Format Nomor HP","cat":"indonesia","icon":"📱","desc":"08xx ↔ +62 ↔ 62xx.","keywords":"hp,nomor,telepon,62,whatsapp","file":"tools/indonesia/format-hp.js"},
  {"id":"hijriah","name":"Konverter Hijriah","cat":"indonesia","icon":"🌙","desc":"Konversi Masehi ↔ Hijriah dua arah.","keywords":"hijriah,kalender,islam,puasa,lebaran,ramadhan","file":"tools/indonesia/hijriah.js"},
  {"id":"patungan","name":"Kalkulator Patungan","cat":"indonesia","icon":"🧾","desc":"Split bill + pajak & service.","keywords":"patungan,split,bill,bayar,bareng","file":"tools/indonesia/patungan.js"},
  {"id":"plat-nomor","name":"Cek Asal Plat Nomor","cat":"indonesia","icon":"🚗","desc":"Asal daerah dari kode plat kendaraan.","keywords":"plat,nomor,kendaraan,motor,mobil,daerah","file":"tools/indonesia/plat-nomor.js"},
  {"id":"pph21","name":"Kalkulator PPh 21","cat":"indonesia","icon":"🧾","desc":"Hitung PPh 21 karyawan + PTKP.","keywords":"gaji,pajak,penghasilan,pph,karyawan","file":"tools/indonesia/pph21.js"},
  {"id":"thr","name":"Kalkulator THR","cat":"indonesia","icon":"🧧","desc":"THR proporsional sesuai masa kerja.","keywords":"thr,bonus,lebaran,gaji","file":"tools/indonesia/thr.js"},
  {"id":"weton","name":"Weton Jawa","cat":"indonesia","icon":"🗓️","desc":"Hitung weton & pasaran dari tanggal lahir.","keywords":"weton,jawa,pasaran,lahir,primbon","file":"tools/indonesia/weton.js"},
  {"id":"zakat","name":"Kalkulator Zakat","cat":"indonesia","icon":"🤲","desc":"Zakat maal & fitrah.","keywords":"zakat,maal,fitrah,islam","file":"tools/indonesia/zakat.js"},
  {"id":"zona-waktu","name":"Konverter Zona Waktu","cat":"indonesia","icon":"🕐","desc":"WIB, WITA, WIT + kota dunia.","keywords":"waktu,zona,wib,wita,wit,jam","file":"tools/indonesia/zona-waktu.js"},
  {"id":"bcrypt","name":"Bcrypt Hasher","cat":"keamanan","icon":"🔐","desc":"Hash password ala bcrypt + verifikasi.","keywords":"bcrypt,hash,password","file":"tools/keamanan/bcrypt.js"},
  {"id":"hash-generator","name":"Hash Generator","cat":"keamanan","icon":"#️⃣","desc":"Hash teks ke MD5, SHA-1, SHA-256, SHA-512.","keywords":"hash,md5,sha","file":"tools/keamanan/hash-generator.js"},
  {"id":"hmac-generator","name":"HMAC Generator","cat":"keamanan","icon":"🔏","desc":"Buat HMAC-SHA256/SHA-512 dari teks + secret key.","keywords":"hmac,sha,secret,api","file":"tools/keamanan/hmac-generator.js"},
  {"id":"passphrase","name":"Passphrase Indonesia","cat":"keamanan","icon":"🔑","desc":"Passphrase kata Indonesia yang kuat.","keywords":"passphrase,kata,sandi,aman,indonesia","file":"tools/keamanan/passphrase.js"},
  {"id":"password-generator","name":"Password Generator","cat":"keamanan","icon":"🔑","desc":"Buat password kuat yang susah ditebak.","keywords":"password,sandi,aman,kuat,acak","file":"tools/keamanan/password-generator.js"},
  {"id":"password-strength","name":"Cek Kekuatan Password","cat":"keamanan","icon":"🛡️","desc":"Ukur seberapa kuat password kamu.","keywords":"password,kuat,cek,sandi","file":"tools/keamanan/password-strength.js"},
  {"id":"totp-generator","name":"OTP Authenticator","cat":"keamanan","icon":"⏱️","desc":"Kode OTP 30-detik dari secret (kayak Google Authenticator).","keywords":"otp,authenticator,2fa,kode","file":"tools/keamanan/totp-generator.js"},
  {"id":"uuid-generator","name":"UUID Generator","cat":"keamanan","icon":"🆔","desc":"Buat UUID v4 acak.","keywords":"uuid,acak,id","file":"tools/keamanan/uuid-generator.js"},
  {"id":"kurs-cuaca","name":"Kurs & Cuaca","cat":"liveapi","icon":"💱","desc":"Kurs mata uang live & cuaca kota.","keywords":"kurs,dollar,uang,cuaca,rupiah","file":"tools/liveapi/kurs-cuaca.js"},
  {"id":"audio-trimmer","name":"Audio Trimmer","cat":"musik","icon":"✂️","desc":"Potong audio di browser, export WAV.","keywords":"audio,potong,mp3,trim","file":"tools/musik/audio-trimmer.js"},
  {"id":"camelot","name":"Camelot Wheel","cat":"musik","icon":"🎧","desc":"Kunci lagu untuk DJ mixing.","keywords":"camelot,dj,kunci,mix","file":"tools/musik/camelot.js"},
  {"id":"chord-transpose","name":"Chord Transposer","cat":"musik","icon":"🎸","desc":"Naik-turunkan kunci chord lagu.","keywords":"chord,kunci,gitar,lagu,transpose","file":"tools/musik/chord-transpose.js"},
  {"id":"drum-machine","name":"Drum Machine","cat":"musik","icon":"🎛️","desc":"Step sequencer drum sederhana.","keywords":"drum,beat,musik","file":"tools/musik/drum-machine.js"},
  {"id":"metronome","name":"Metronom","cat":"musik","icon":"🥁","desc":"Metronom dengan birama.","keywords":"metronom,tempo,ketuk","file":"tools/musik/metronome.js"},
  {"id":"piano","name":"Piano Browser","cat":"musik","icon":"🎹","desc":"Main piano di browser.","keywords":"piano,main,musik","file":"tools/musik/piano.js"},
  {"id":"playlist-duration","name":"Durasi Playlist","cat":"musik","icon":"📃","desc":"Total durasi dari daftar lagu.","keywords":"playlist,durasi,lagu","file":"tools/musik/playlist-duration.js"},
  {"id":"tap-bpm","name":"Tap BPM","cat":"musik","icon":"👆","desc":"Ketuk layar untuk deteksi tempo.","keywords":"bpm,tempo,ketuk,dj","file":"tools/musik/tap-bpm.js"},
  {"id":"tts","name":"Text-to-Speech","cat":"musik","icon":"🗣️","desc":"Bacakan teks bahasa Indonesia.","keywords":"tts,suara,baca,teks","file":"tools/musik/tts.js"},
  {"id":"white-noise","name":"White Noise","cat":"musik","icon":"🌧️","desc":"Suara fokus & tidur.","keywords":"noise,tidur,fokus,suara,hujan","file":"tools/musik/white-noise.js"},
  {"id":"citation","name":"Citation Generator","cat":"pelajar","icon":"📚","desc":"Daftar pustaka APA & MLA.","keywords":"citation,sitasi,skripsi,daftar,pustaka","file":"tools/pelajar/citation.js"},
  {"id":"ipk","name":"Kalkulator IPK","cat":"pelajar","icon":"🎓","desc":"Hitung IPK semester.","keywords":"ipk,nilai,kuliah,semester","file":"tools/pelajar/ipk.js"},
  {"id":"typing-test","name":"Tes Mengetik","cat":"pelajar","icon":"🚀","desc":"Kecepatan mengetik Indonesia.","keywords":"mengetik,kecepatan,keyboard,tes","file":"tools/pelajar/typing-test.js"},
  {"id":"pomodoro","name":"Pomodoro Timer","cat":"produktivitas","icon":"🍅","desc":"Timer fokus 25/5.","keywords":"pomodoro,fokus,timer,belajar","file":"tools/produktivitas/pomodoro.js"},
  {"id":"sleep-cycle","name":"Siklus Tidur","cat":"produktivitas","icon":"😴","desc":"Jam bangun ideal per 90 menit.","keywords":"tidur,bangun,siklus,jam","file":"tools/produktivitas/sleep-cycle.js"},
  {"id":"water-tracker","name":"Tracker Air Minum","cat":"produktivitas","icon":"💧","desc":"Target minum harian.","keywords":"air,minum,sehat,tracker","file":"tools/produktivitas/water-tracker.js"},
  {"id":"age-calc","name":"Kalkulator Umur","cat":"sehari","icon":"🎂","desc":"Umur presisi tahun-bulan-hari.","keywords":"umur,usia,lahir,tanggal","file":"tools/sehari/age-calc.js"},
  {"id":"bmi","name":"BMI & Kalori","cat":"sehari","icon":"⚕️","desc":"BMI + estimasi kebutuhan kalori.","keywords":"bmi,berat,badan,diet,kalori","file":"tools/sehari/bmi.js"},
  {"id":"date-duration","name":"Durasi Tanggal","cat":"sehari","icon":"📅","desc":"Durasi antara dua tanggal.","keywords":"tanggal,durasi,selisih,hari","file":"tools/sehari/date-duration.js"},
  {"id":"pantun","name":"Pantun Pembuka","cat":"sehari","icon":"🎭","desc":"Template pantun buat presentasi.","keywords":"pantun,presentasi,pembuka","file":"tools/sehari/pantun.js"},
  {"id":"stopwatch","name":"Stopwatch","cat":"sehari","icon":"🏁","desc":"Stopwatch + catat lap.","keywords":"stopwatch,waktu,lap,timer","file":"tools/sehari/stopwatch.js"},
  {"id":"ascii-art","name":"ASCII Art","cat":"teks","icon":"⌨️","desc":"Teks jadi seni ASCII.","keywords":"ascii,seni,teks","file":"tools/teks/ascii-art.js"},
  {"id":"dedup-sort","name":"Dedup & Urutkan","cat":"teks","icon":"🧲","desc":"Hapus duplikat & urutkan baris.","keywords":"duplikat,urut,baris,sort","file":"tools/teks/dedup-sort.js"},
  {"id":"extract-contact","name":"Ekstrak Kontak","cat":"teks","icon":"📇","desc":"Ambil email & nomor HP dari teks.","keywords":"kontak,email,nomor,ekstrak","file":"tools/teks/extract-contact.js"},
  {"id":"fancy-text","name":"Fancy Text","cat":"teks","icon":"✨","desc":"Teks gaya unik untuk sosmed.","keywords":"fancy,teks,sosmed,keren,gaya","file":"tools/teks/fancy-text.js"},
  {"id":"lorem-ipsum","name":"Lorem Ipsum Generator","cat":"teks","icon":"📄","desc":"Generator teks dummy.","keywords":"lorem,dummy,teks","file":"tools/teks/lorem-ipsum.js"},
  {"id":"sensor-teks","name":"Sensor Teks","cat":"teks","icon":"🙈","desc":"Sensor kata/nomor otomatis.","keywords":"sensor,kata,kasar,privasi","file":"tools/teks/sensor-teks.js"},
  {"id":"text-diff","name":"Pembanding Teks","cat":"teks","icon":"🔀","desc":"Bandingkan dua teks.","keywords":"diff,banding,teks","file":"tools/teks/text-diff.js"},
  {"id":"wa-formatter","name":"WA Text Formatter","cat":"teks","icon":"✍️","desc":"Teks biasa jadi format WhatsApp.","keywords":"whatsapp,wa,format,teks,bold","file":"tools/teks/wa-formatter.js"},
  {"id":"word-counter","name":"Penghitung Kata","cat":"teks","icon":"🔡","desc":"Kata, karakter, estimasi baca.","keywords":"kata,hitung,karakter,skripsi","file":"tools/teks/word-counter.js"},
  {"id":"zalgo","name":"Zalgo Text","cat":"teks","icon":"🌀","desc":"Teks rusak ala zalgo.","keywords":"zalgo,rusak,teks,lucu","file":"tools/teks/zalgo.js"},
];
