/* ADIP Tools v4.2.0 — manifest metadata (GENERATED, jangan edit manual).
   Dibangkitkan oleh scripts/split-tools.py dari folder tools per kategori.
   Berisi metadata ringan untuk home/search/palette; kode tool di-load on-demand.
*/
export const VERSION = '4.2.0';
export const manifest = [
  {"id": "banding-harga", "name": "Perbandingan Harga", "cat": "bisnis", "icon": "⚖️", "desc": "Mana lebih hemat per unit?", "file": "tools/bisnis/banding-harga.js"},
  {"id": "cat-tembok", "name": "Kalkulator Cat", "cat": "bisnis", "icon": "🪣", "desc": "Kebutuhan cat dari luas ruangan.", "file": "tools/bisnis/cat-tembok.js"},
  {"id": "harga-jual", "name": "Kalkulator Harga Jual", "cat": "bisnis", "icon": "💰", "desc": "Modal + margin jadi harga jual.", "file": "tools/bisnis/harga-jual.js"},
  {"id": "invoice", "name": "Invoice Generator", "cat": "bisnis", "icon": "📑", "desc": "Bikin invoice rapi siap cetak.", "file": "tools/bisnis/invoice.js"},
  {"id": "base64", "name": "Base64 Encode/Decode", "cat": "converter", "icon": "🔤", "desc": "Encode & decode Base64, termasuk varian URL-safe.", "file": "tools/converter/base64.js"},
  {"id": "case-converter", "name": "Case Converter", "cat": "converter", "icon": "✏️", "desc": "camelCase, snake_case, kebab-case, Title Case, dll.", "file": "tools/converter/case-converter.js"},
  {"id": "color-converter", "name": "Konverter Warna", "cat": "converter", "icon": "🎨", "desc": "Konversi HEX, RGB, HSL + preview.", "file": "tools/converter/color-converter.js"},
  {"id": "cooking-converter", "name": "Takaran Masak", "cat": "converter", "icon": "U0001f373", "desc": "Konversi sendok, cup, gram, ml.", "file": "tools/converter/cooking-converter.js"},
  {"id": "image-base64", "name": "Gambar ke Base64", "cat": "converter", "icon": "🖼️", "desc": "Gambar jadi string Base64 siap embed.", "file": "tools/converter/image-base64.js"},
  {"id": "json-yaml", "name": "JSON ↔ YAML", "cat": "converter", "icon": "⇄", "desc": "Konversi JSON ke YAML dan sebaliknya.", "file": "tools/converter/json-yaml.js"},
  {"id": "morse", "name": "Sandi Morse", "cat": "converter", "icon": "📻", "desc": "Teks ↔ sandi Morse + bunyi.", "file": "tools/converter/morse.js"},
  {"id": "number-converter", "name": "Konverter Angka", "cat": "converter", "icon": "🔢", "desc": "Biner, oktal, desimal, hex, dan romawi.", "file": "tools/converter/number-converter.js"},
  {"id": "slug-generator", "name": "Slug Generator", "cat": "converter", "icon": "🏷️", "desc": "Judul jadi slug URL yang rapi.", "file": "tools/converter/slug-generator.js"},
  {"id": "terbilang", "name": "Terbilang Indonesia", "cat": "converter", "icon": "💬", "desc": "Angka jadi kata bahasa Indonesia.", "file": "tools/converter/terbilang.js"},
  {"id": "unit-converter", "name": "Konverter Satuan", "cat": "converter", "icon": "📏", "desc": "Panjang, berat, suhu, volume, kecepatan.", "file": "tools/converter/unit-converter.js"},
  {"id": "unix-timestamp", "name": "Unix Timestamp", "cat": "converter", "icon": "🕰️", "desc": "Unix timestamp ↔ tanggal (WIB).", "file": "tools/converter/unix-timestamp.js"},
  {"id": "url-encoder", "name": "URL Encoder/Decoder", "cat": "converter", "icon": "🔗", "desc": "Encode/decode URL & komponennya.", "file": "tools/converter/url-encoder.js"},
  {"id": "barcode", "name": "vCard QR & Barcode", "cat": "desain", "icon": "🧾", "desc": "QR kontak vCard & barcode produk.", "file": "tools/desain/barcode.js"},
  {"id": "boxshadow", "name": "Box-Shadow Generator", "cat": "desain", "icon": "🌓", "desc": "Atur bayangan visual + copy CSS.", "file": "tools/desain/boxshadow.js"},
  {"id": "favicon", "name": "Favicon Generator", "cat": "desain", "icon": "⭐", "desc": "Bikin favicon dari emoji/teks.", "file": "tools/desain/favicon.js"},
  {"id": "gradient", "name": "Gradient Generator", "cat": "desain", "icon": "🌈", "desc": "Bikin gradient CSS + preview.", "file": "tools/desain/gradient.js"},
  {"id": "palette", "name": "Color Palette Generator", "cat": "desain", "icon": "🎨", "desc": "Palet warna harmonis sekali klik.", "file": "tools/desain/palette.js"},
  {"id": "qr-generator", "name": "QR Code Generator", "cat": "desain", "icon": "⬛", "desc": "QR Code teks, URL, & WiFi.", "file": "tools/desain/qr-generator.js"},
  {"id": "chmod", "name": "Kalkulator Chmod", "cat": "developer", "icon": "🔒", "desc": "Permission oktal ↔ simbolik.", "file": "tools/developer/chmod.js"},
  {"id": "cron", "name": "Cron Parser & Builder", "cat": "developer", "icon": "⏰", "desc": "Terjemahkan & susun cron expression.", "file": "tools/developer/cron.js"},
  {"id": "dns-lookup", "name": "DNS Lookup", "cat": "developer", "icon": "📡", "desc": "Lookup DNS via Google DNS-over-HTTPS.", "file": "tools/developer/dns-lookup.js"},
  {"id": "html-table", "name": "Generator Tabel HTML", "cat": "developer", "icon": "📋", "desc": "Bikin tabel HTML dari data baris.", "file": "tools/developer/html-table.js"},
  {"id": "json-formatter", "name": "JSON Formatter", "cat": "developer", "icon": "🧩", "desc": "Rapikan, minify, & validasi JSON.", "file": "tools/developer/json-formatter.js"},
  {"id": "json-table", "name": "JSON ke Tabel", "cat": "developer", "icon": "📊", "desc": "Paste JSON jadi tabel yang enak dibaca.", "file": "tools/developer/json-table.js"},
  {"id": "jwt-parser", "name": "JWT Parser", "cat": "developer", "icon": "🎫", "desc": "Baca isi header & payload JWT.", "file": "tools/developer/jwt-parser.js"},
  {"id": "markdown-preview", "name": "Markdown Preview", "cat": "developer", "icon": "📝", "desc": "Preview Markdown jadi HTML.", "file": "tools/developer/markdown-preview.js"},
  {"id": "meta-generator", "name": "Meta Tag Generator", "cat": "developer", "icon": "🏷️", "desc": "Generator meta tag SEO lengkap.", "file": "tools/developer/meta-generator.js"},
  {"id": "og-preview", "name": "Open Graph Preview", "cat": "developer", "icon": "👁️", "desc": "Preview tampilan link di medsos.", "file": "tools/developer/og-preview.js"},
  {"id": "regex-tester", "name": "Regex Tester", "cat": "developer", "icon": "🔍", "desc": "Tes regex + highlight hasil.", "file": "tools/developer/regex-tester.js"},
  {"id": "robots-generator", "name": "Robots.txt Generator", "cat": "developer", "icon": "🤖", "desc": "Susun file robots.txt.", "file": "tools/developer/robots-generator.js"},
  {"id": "sql-formatter", "name": "SQL Formatter", "cat": "developer", "icon": "🗄️", "desc": "Rapikan query SQL.", "file": "tools/developer/sql-formatter.js"},
  {"id": "subnet", "name": "Kalkulator Subnet IPv4", "cat": "developer", "icon": "🌐", "desc": "Network, broadcast, range host dari CIDR.", "file": "tools/developer/subnet.js"},
  {"id": "xml-formatter", "name": "XML Formatter", "cat": "developer", "icon": "📰", "desc": "Rapikan & validasi XML.", "file": "tools/developer/xml-formatter.js"},
  {"id": "zerowidth", "name": "Detektor Karakter Tak Terlihat", "cat": "developer", "icon": "👻", "desc": "Temukan zero-width & karakter aneh di teks.", "file": "tools/developer/zerowidth.js"},
  {"id": "baby-name", "name": "Nama Bayi", "cat": "fun", "icon": "👶", "desc": "Nama bayi Indonesia + arti.", "file": "tools/fun/baby-name.js"},
  {"id": "couple-days", "name": "Hari Jadian", "cat": "fun", "icon": "💑", "desc": "Sudah berapa hari bareng?", "file": "tools/fun/couple-days.js"},
  {"id": "decision", "name": "Pengacak Keputusan", "cat": "fun", "icon": "🔮", "desc": "Bantu ambil keputusan.", "file": "tools/fun/decision.js"},
  {"id": "dice", "name": "Dadu", "cat": "fun", "icon": "🎲", "desc": "Lempar dadu + riwayat.", "file": "tools/fun/dice.js"},
  {"id": "reaction", "name": "Tes Refleks", "cat": "fun", "icon": "⚡", "desc": "Ukur kecepatan refleks.", "file": "tools/fun/reaction.js"},
  {"id": "spinwheel", "name": "Roda Putar", "cat": "fun", "icon": "🎡", "desc": "Spin wheel visual.", "file": "tools/fun/spinwheel.js"},
  {"id": "aspect-ratio", "name": "Kalkulator Rasio", "cat": "gambar", "icon": "📐", "desc": "Rasio aspek & resolusi.", "file": "tools/gambar/aspect-ratio.js"},
  {"id": "exif-clean", "name": "Hapus EXIF", "cat": "gambar", "icon": "🧹", "desc": "Bersihkan metadata sebelum dishare.", "file": "tools/gambar/exif-clean.js"},
  {"id": "image-compress", "name": "Kompres Gambar", "cat": "gambar", "icon": "🗜️", "desc": "Kecilkan ukuran foto langsung di HP.", "file": "tools/gambar/image-compress.js"},
  {"id": "image-convert", "name": "Convert Gambar", "cat": "gambar", "icon": "🔁", "desc": "Convert WebP/JPG/PNG di browser.", "file": "tools/gambar/image-convert.js"},
  {"id": "yt-thumbnail", "name": "Thumbnail YouTube", "cat": "gambar", "icon": "📺", "desc": "Download thumbnail YouTube dari URL.", "file": "tools/gambar/yt-thumbnail.js"},
  {"id": "arisan", "name": "Arisan Picker", "cat": "indonesia", "icon": "🎰", "desc": "Kocok nama anggota arisan.", "file": "tools/indonesia/arisan.js"},
  {"id": "bunga-majemuk", "name": "Bunga Majemuk", "cat": "indonesia", "icon": "📈", "desc": "Simulasi compound interest.", "file": "tools/indonesia/bunga-majemuk.js"},
  {"id": "cicilan", "name": "Kalkulator Cicilan", "cat": "indonesia", "icon": "🏍️", "desc": "Simulasi cicilan flat & anuitas.", "file": "tools/indonesia/cicilan.js"},
  {"id": "countdown", "name": "Countdown Acara", "cat": "indonesia", "icon": "🎉", "desc": "Hitung mundur ke hari penting.", "file": "tools/indonesia/countdown.js"},
  {"id": "diskon", "name": "Diskon Bertingkat", "cat": "indonesia", "icon": "💸", "desc": "Hitung diskon berlapis yang benar.", "file": "tools/indonesia/diskon.js"},
  {"id": "format-hp", "name": "Format Nomor HP", "cat": "indonesia", "icon": "📱", "desc": "08xx ↔ +62 ↔ 62xx.", "file": "tools/indonesia/format-hp.js"},
  {"id": "patungan", "name": "Kalkulator Patungan", "cat": "indonesia", "icon": "🧾", "desc": "Split bill + pajak & service.", "file": "tools/indonesia/patungan.js"},
  {"id": "thr", "name": "Kalkulator THR", "cat": "indonesia", "icon": "🧧", "desc": "THR proporsional sesuai masa kerja.", "file": "tools/indonesia/thr.js"},
  {"id": "weton", "name": "Weton Jawa", "cat": "indonesia", "icon": "🗓️", "desc": "Hitung weton & pasaran dari tanggal lahir.", "file": "tools/indonesia/weton.js"},
  {"id": "zakat", "name": "Kalkulator Zakat", "cat": "indonesia", "icon": "🤲", "desc": "Zakat maal & fitrah.", "file": "tools/indonesia/zakat.js"},
  {"id": "zona-waktu", "name": "Konverter Zona Waktu", "cat": "indonesia", "icon": "🕐", "desc": "WIB, WITA, WIT + kota dunia.", "file": "tools/indonesia/zona-waktu.js"},
  {"id": "bcrypt", "name": "Bcrypt Hasher", "cat": "keamanan", "icon": "🔐", "desc": "Hash password ala bcrypt + verifikasi.", "file": "tools/keamanan/bcrypt.js"},
  {"id": "hash-generator", "name": "Hash Generator", "cat": "keamanan", "icon": "#️⃣", "desc": "Hash teks ke MD5, SHA-1, SHA-256, SHA-512.", "file": "tools/keamanan/hash-generator.js"},
  {"id": "hmac-generator", "name": "HMAC Generator", "cat": "keamanan", "icon": "🔏", "desc": "Buat HMAC-SHA256/SHA-512 dari teks + secret key.", "file": "tools/keamanan/hmac-generator.js"},
  {"id": "password-generator", "name": "Password Generator", "cat": "keamanan", "icon": "🔑", "desc": "Buat password kuat yang susah ditebak.", "file": "tools/keamanan/password-generator.js"},
  {"id": "password-strength", "name": "Cek Kekuatan Password", "cat": "keamanan", "icon": "🛡️", "desc": "Ukur seberapa kuat password kamu.", "file": "tools/keamanan/password-strength.js"},
  {"id": "totp-generator", "name": "OTP Authenticator", "cat": "keamanan", "icon": "⏱️", "desc": "Kode OTP 30-detik dari secret (kayak Google Authenticator).", "file": "tools/keamanan/totp-generator.js"},
  {"id": "uuid-generator", "name": "UUID Generator", "cat": "keamanan", "icon": "🆔", "desc": "Buat UUID v4 acak.", "file": "tools/keamanan/uuid-generator.js"},
  {"id": "kurs-cuaca", "name": "Kurs & Cuaca", "cat": "liveapi", "icon": "💱", "desc": "Kurs mata uang live & cuaca kota.", "file": "tools/liveapi/kurs-cuaca.js"},
  {"id": "audio-trimmer", "name": "Audio Trimmer", "cat": "musik", "icon": "✂️", "desc": "Potong audio di browser, export WAV.", "file": "tools/musik/audio-trimmer.js"},
  {"id": "camelot", "name": "Camelot Wheel", "cat": "musik", "icon": "🎧", "desc": "Kunci lagu untuk DJ mixing.", "file": "tools/musik/camelot.js"},
  {"id": "chord-transpose", "name": "Chord Transposer", "cat": "musik", "icon": "🎸", "desc": "Naik-turunkan kunci chord lagu.", "file": "tools/musik/chord-transpose.js"},
  {"id": "drum-machine", "name": "Drum Machine", "cat": "musik", "icon": "🎛️", "desc": "Step sequencer drum sederhana.", "file": "tools/musik/drum-machine.js"},
  {"id": "metronome", "name": "Metronom", "cat": "musik", "icon": "🥁", "desc": "Metronom dengan birama.", "file": "tools/musik/metronome.js"},
  {"id": "piano", "name": "Piano Browser", "cat": "musik", "icon": "🎹", "desc": "Main piano di browser.", "file": "tools/musik/piano.js"},
  {"id": "playlist-duration", "name": "Durasi Playlist", "cat": "musik", "icon": "📃", "desc": "Total durasi dari daftar lagu.", "file": "tools/musik/playlist-duration.js"},
  {"id": "tap-bpm", "name": "Tap BPM", "cat": "musik", "icon": "👆", "desc": "Ketuk layar untuk deteksi tempo.", "file": "tools/musik/tap-bpm.js"},
  {"id": "tts", "name": "Text-to-Speech", "cat": "musik", "icon": "🗣️", "desc": "Bacakan teks bahasa Indonesia.", "file": "tools/musik/tts.js"},
  {"id": "white-noise", "name": "White Noise", "cat": "musik", "icon": "🌧️", "desc": "Suara fokus & tidur.", "file": "tools/musik/white-noise.js"},
  {"id": "citation", "name": "Citation Generator", "cat": "pelajar", "icon": "📚", "desc": "Daftar pustaka APA & MLA.", "file": "tools/pelajar/citation.js"},
  {"id": "ipk", "name": "Kalkulator IPK", "cat": "pelajar", "icon": "🎓", "desc": "Hitung IPK semester.", "file": "tools/pelajar/ipk.js"},
  {"id": "typing-test", "name": "Tes Mengetik", "cat": "pelajar", "icon": "🚀", "desc": "Kecepatan mengetik Indonesia.", "file": "tools/pelajar/typing-test.js"},
  {"id": "pomodoro", "name": "Pomodoro Timer", "cat": "produktivitas", "icon": "🍅", "desc": "Timer fokus 25/5.", "file": "tools/produktivitas/pomodoro.js"},
  {"id": "sleep-cycle", "name": "Siklus Tidur", "cat": "produktivitas", "icon": "😴", "desc": "Jam bangun ideal per 90 menit.", "file": "tools/produktivitas/sleep-cycle.js"},
  {"id": "water-tracker", "name": "Tracker Air Minum", "cat": "produktivitas", "icon": "💧", "desc": "Target minum harian.", "file": "tools/produktivitas/water-tracker.js"},
  {"id": "age-calc", "name": "Kalkulator Umur", "cat": "sehari", "icon": "🎂", "desc": "Umur presisi tahun-bulan-hari.", "file": "tools/sehari/age-calc.js"},
  {"id": "bmi", "name": "BMI & Kalori", "cat": "sehari", "icon": "⚕️", "desc": "BMI + estimasi kebutuhan kalori.", "file": "tools/sehari/bmi.js"},
  {"id": "date-duration", "name": "Durasi Tanggal", "cat": "sehari", "icon": "📅", "desc": "Durasi antara dua tanggal.", "file": "tools/sehari/date-duration.js"},
  {"id": "pantun", "name": "Pantun Pembuka", "cat": "sehari", "icon": "🎭", "desc": "Template pantun buat presentasi.", "file": "tools/sehari/pantun.js"},
  {"id": "stopwatch", "name": "Stopwatch", "cat": "sehari", "icon": "🏁", "desc": "Stopwatch + catat lap.", "file": "tools/sehari/stopwatch.js"},
  {"id": "ascii-art", "name": "ASCII Art", "cat": "teks", "icon": "⌨️", "desc": "Teks jadi seni ASCII.", "file": "tools/teks/ascii-art.js"},
  {"id": "dedup-sort", "name": "Dedup & Urutkan", "cat": "teks", "icon": "🧲", "desc": "Hapus duplikat & urutkan baris.", "file": "tools/teks/dedup-sort.js"},
  {"id": "extract-contact", "name": "Ekstrak Kontak", "cat": "teks", "icon": "📇", "desc": "Ambil email & nomor HP dari teks.", "file": "tools/teks/extract-contact.js"},
  {"id": "fancy-text", "name": "Fancy Text", "cat": "teks", "icon": "✨", "desc": "Teks gaya unik untuk sosmed.", "file": "tools/teks/fancy-text.js"},
  {"id": "lorem-ipsum", "name": "Lorem Ipsum Generator", "cat": "teks", "icon": "📄", "desc": "Generator teks dummy.", "file": "tools/teks/lorem-ipsum.js"},
  {"id": "sensor-teks", "name": "Sensor Teks", "cat": "teks", "icon": "🙈", "desc": "Sensor kata/nomor otomatis.", "file": "tools/teks/sensor-teks.js"},
  {"id": "text-diff", "name": "Pembanding Teks", "cat": "teks", "icon": "🔀", "desc": "Bandingkan dua teks.", "file": "tools/teks/text-diff.js"},
  {"id": "wa-formatter", "name": "WA Text Formatter", "cat": "teks", "icon": "✍️", "desc": "Teks biasa jadi format WhatsApp.", "file": "tools/teks/wa-formatter.js"},
  {"id": "word-counter", "name": "Penghitung Kata", "cat": "teks", "icon": "🔡", "desc": "Kata, karakter, estimasi baca.", "file": "tools/teks/word-counter.js"},
  {"id": "zalgo", "name": "Zalgo Text", "cat": "teks", "icon": "🌀", "desc": "Teks rusak ala zalgo.", "file": "tools/teks/zalgo.js"},
];
